import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased 
                     min-h-screen flex flex-col items-center`}
      >
        {/* TÍTULO CENTRADO */}
        <h1 className="text-3xl font-bold mt-6 mb-4 text-center">
          Menú principal
        </h1>

        {/* CONTENEDOR CENTRADO */}
        <main className="flex flex-col items-center justify-center w-full px-4">
          {children}
        </main>
      </body>
    </html>
  );
}
